unpackaged/main/default/objects/Barrel__c/Barrel__c.object-meta.xml
<CustomObject>
    <description>Initially created to be utilized in the Single Barrel Program. Stores specific information about a barrel</description>
    <label>Barrel</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Barrel Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Barrels</pluralLabel>
    <sharingModel>Read</sharingModel>
    <sharingReasons>
        <fullName>test__c</fullName>
        <label>test</label>
    </sharingReasons>
</CustomObject>

unpackaged/main/default/objects/Barrel__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Cruzan</fullName>
            </value>
            <value>
                <fullName>El Tesoro</fullName>
            </value>
            <value>
                <fullName>Jim Beam</fullName>
            </value>
            <value>
                <fullName>Knob Creek</fullName>
            </value>
            <value>
                <fullName>Makers Mark</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Barrel__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Barrels</relationshipLabel>
    <relationshipName>Barrels</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Barrel__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Brand__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Product_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Barrel__c/fields/Sample_Kit__c.field-meta.xml
<CustomField>
    <fullName>Sample_Kit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sample Kit</label>
    <referenceTo>Sample_Kit__c</referenceTo>
    <relationshipLabel>Barrels</relationshipLabel>
    <relationshipName>Barrels</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Barrel__c/fields/Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Number__c</fullName>
    <label>Tracking Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Barrel__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Knob Creek</fullName>
            </value>
            <value>
                <fullName>Jim Beam</fullName>
            </value>
            <value>
                <fullName>Cruzan</fullName>
            </value>
            <value>
                <fullName>Makers Mark</fullName>
            </value>
            <value>
                <fullName>El Tesoro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Barrel_Order_Group__c/Barrel_Order_Group__c.object-meta.xml
<CustomObject>
    <description>Initially created for the Single Barrel Program.  This object is used to group orders that are placed at the same time by a sales rep for the same account.</description>
    <label>Barrel Order Group</label>
    <nameField>
        <displayFormat>Barrel Group-{00000}</displayFormat>
        <label>Barrel Order Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Barrel Order Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Barrel_Order_Group__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trip and Tour</fullName>
            </value>
            <value>
                <fullName>Sample Kit</fullName>
            </value>
            <value>
                <fullName>Distiller's Choice</fullName>
            </value>
            <value>
                <fullName>Split Barrel</fullName>
            </value>
            <value>
                <fullName>Remote Selection</fullName>
            </value>
            <value>
                <fullName>Recent Recipes</fullName>
            </value>
            <value>
                <fullName>Date Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <description>SB-MC-SB-10-this object will store Brand details in it.</description>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Case/fields/Barrel__c.field-meta.xml
<CustomField>
    <fullName>Barrel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Barrel</label>
    <referenceTo>Barrel__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Barrel_Order_Group__c.field-meta.xml
<CustomField>
    <fullName>Barrel_Order_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Barrel Order Group</label>
    <referenceTo>Barrel_Order_Group__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <description>The brand that is used in the Brand Registration process.</description>
    <inlineHelpText>Brand that is being registered</inlineHelpText>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>(ri)1</fullName>
            </value>
            <value>
                <fullName>100 Anos</fullName>
            </value>
            <value>
                <fullName>2 Gingers</fullName>
            </value>
            <value>
                <fullName>Aftershock</fullName>
            </value>
            <value>
                <fullName>Alberta Premium</fullName>
            </value>
            <value>
                <fullName>Alberta Pure</fullName>
            </value>
            <value>
                <fullName>Alberta Rye</fullName>
            </value>
            <value>
                <fullName>Alberta Springs</fullName>
            </value>
            <value>
                <fullName>AO</fullName>
            </value>
            <value>
                <fullName>Ardmore</fullName>
            </value>
            <value>
                <fullName>Auchentoshan</fullName>
            </value>
            <value>
                <fullName>Baker's</fullName>
            </value>
            <value>
                <fullName>Banff Ice</fullName>
            </value>
            <value>
                <fullName>Banff Summit</fullName>
            </value>
            <value>
                <fullName>Basil Hayden's</fullName>
            </value>
            <value>
                <fullName>Beam Suntory Corporate</fullName>
            </value>
            <value>
                <fullName>Booker's</fullName>
            </value>
            <value>
                <fullName>Bowmore</fullName>
            </value>
            <value>
                <fullName>Bruxo</fullName>
            </value>
            <value>
                <fullName>Calico Jack</fullName>
            </value>
            <value>
                <fullName>Canadian Club</fullName>
            </value>
            <value>
                <fullName>Canadian Club RTD</fullName>
            </value>
            <value>
                <fullName>Castellana</fullName>
            </value>
            <value>
                <fullName>CHITA</fullName>
                <label>Chita</label>
            </value>
            <value>
                <fullName>Conch</fullName>
            </value>
            <value>
                <fullName>Connemara</fullName>
            </value>
            <value>
                <fullName>Courvoisier</fullName>
            </value>
            <value>
                <fullName>Cruzan</fullName>
            </value>
            <value>
                <fullName>DeKuyper</fullName>
            </value>
            <value>
                <fullName>DYC</fullName>
            </value>
            <value>
                <fullName>Knob Creek</fullName>
            </value>
            <value>
                <fullName>Makers Mark</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/CcEmail__c.field-meta.xml
<CustomField>
    <fullName>CcEmail__c</fullName>
    <label>CcEmail</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Brand__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Product_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Sample_Kit__c/Sample_Kit__c.object-meta.xml
<CustomObject>
    <label>Sample Kit</label>
    <nameField>
        <displayFormat>Sample Kit-{0000}</displayFormat>
        <label>Sample Kit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Kits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Sample_Kit__c/fields/Barrel_Order_Group__c.field-meta.xml
<CustomField>
    <fullName>Barrel_Order_Group__c</fullName>
    <label>Barrel Order Group</label>
    <referenceTo>Barrel_Order_Group__c</referenceTo>
    <relationshipLabel>Sample Kits</relationshipLabel>
    <relationshipName>Sample_Kits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Sample_Kit__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Sample Kits</relationshipLabel>
    <relationshipName>Sample_Kits</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Sample_Kit__c/fields/Delivery_Status__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Status__c</fullName>
    <label>Delivery Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>In Transit</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Sample_Kit__c/fields/Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Number__c</fullName>
    <externalId>true</externalId>
    <label>Tracking Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Sample_Kit__c/fields/Tracking_Number_Creation_Date__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Number_Creation_Date__c</fullName>
    <label>Kit Delivery Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/globalValueSets/Product_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>10 YEAR</fullName>
    </customValue>
    <customValue>
        <fullName>10 YEAR SINGLE MALT</fullName>
    </customValue>
    <customValue>
        <fullName>12 YEAR</fullName>
    </customValue>
    <customValue>
        <fullName>15 YEAR</fullName>
    </customValue>
    <customValue>
        <fullName>15 YEAR SINGLE MALT</fullName>
    </customValue>
    <customValue>
        <fullName>17 YEAR</fullName>
    </customValue>
    <customValue>
        <fullName>18 YEAR</fullName>
    </customValue>
    <customValue>
        <fullName>18 YEAR SINGLE MALT</fullName>
    </customValue>
    <customValue>
        <fullName>1961 50 YEAR</fullName>
    </customValue>
    <customValue>
        <fullName>1965</fullName>
    </customValue>
    <customValue>
        <fullName>1988</fullName>
    </customValue>
    <customValue>
        <fullName>21 YEAR</fullName>
    </customValue>
    <customValue>
        <fullName>23 YEAR</fullName>
    </customValue>
    <customValue>
        <fullName>25TH ANNIVERSARY</fullName>
    </customValue>
    <customValue>
        <fullName>25 YEAR</fullName>
    </customValue>
    <customValue>
        <fullName>27 YEAR</fullName>
    </customValue>
    <customValue>
        <fullName>28 YEAR</fullName>
    </customValue>
    <customValue>
        <fullName>30 YEAR</fullName>
    </customValue>
    <customValue>
        <fullName>3 WOOD</fullName>
    </customValue>
    <customValue>
        <fullName>3 YEAR</fullName>
    </customValue>
    <customValue>
        <fullName>46</fullName>
    </customValue>
    <customValue>
        <fullName>50</fullName>
    </customValue>
    <customValue>
        <fullName>ADDITIONAL NOTES</fullName>
    </customValue>
    <customValue>
        <fullName>AGUA FUERTE</fullName>
    </customValue>
    <customValue>
        <fullName>AMERICAN OAK</fullName>
    </customValue>
    <customValue>
        <fullName>ANEJO</fullName>
    </customValue>
    <customValue>
        <fullName>ANEJO CRISTALINO</fullName>
    </customValue>
    <customValue>
        <fullName>APPLE</fullName>
    </customValue>
    <customValue>
        <fullName>BARENAKED VODKA</fullName>
    </customValue>
    <customValue>
        <fullName>BARTENDER&apos;S MALT</fullName>
    </customValue>
    <customValue>
        <fullName>Rye</fullName>
    </customValue>
    <masterLabel>Product Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/SBP_SampleKitRelatedListControllerTest.cls
@isTest(SeeAllData = false)
private class SBP_SampleKitRelatedListControllerTest{
    //test data setup
    @testSetup static void setup(){
        
    }
    public static testMethod void getAllSampleKitsTest(){
        Account testAccount = new Account();
        testAccount.Name = 'Test Account';
        testAccount.BillingState = 'IL';
        testAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('OffPremise').getRecordTypeId();
        insert testAccount;
        
        
        Barrel_Order_Group__c bg = new Barrel_Order_Group__c();
        bg.Type__c = 'Trip and Tour';
        
        Barrel_Order_Group__c bg2 = new Barrel_Order_Group__c();
        bg2.Type__c = 'Trip and Tour';
        
        insert new List<Barrel_Order_Group__c> {bg, bg2};
            
            
        Case c = new Case();
        c.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Single_Barrel_Standard').getRecordTypeId();
        c.Type = 'Trip and Tour';
        c.Barrel_Order_Group__c = bg.Id;
        c.Brand__c = 'Knob Creek';
        c.Product_Type__c = 'Rye';
        c.ccEmail__c = 'test@test.com';
        c.AccountId = testAccount.Id;
        c.Status = 'New';
        
        Case c2 = new Case();
        c2.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Single_Barrel_Proof_Specific').getRecordTypeId();
        c2.Type = 'Trip and Tour';
        c2.Barrel_Order_Group__c = bg2.Id;
        //c2.Brand__c = 'Makers Mark';
        c2.AccountId = testAccount.Id;
        c2.Status = 'New';
        
        insert new List<Case> {c, c2};
        Sample_Kit__c sampleKit = new Sample_Kit__c();
        
        sampleKit.Sample_Selected__c = false;
        sampleKit.Tracking_Number_Creation_Date__c = system.today();
        sampleKit.Barrel_Order_Group__c = bg.Id;
        sampleKit.Delivery_Status__c ='Shipped';
        sampleKit.Tracking_Number__c='test1213';
        sampleKit.Case__c  = c.Id;
        insert sampleKit;
        
        Sample_Kit__c sample2 = new Sample_Kit__c();
        
        sample2.Sample_Selected__c = false;
        sample2.Tracking_Number_Creation_Date__c = system.today();
        sample2.Barrel_Order_Group__c = bg2.Id;
        sample2.Delivery_Status__c ='Shipped';
        sample2.Tracking_Number__c='test23232';
        sample2.Case__c  = c2.Id;
        insert sample2;
        
        //Inserting Barrel as part of create3Samples enhancement     
        Barrel__c barrel = new Barrel__c();
        barrel.Case__c = c.Id;
        insert barrel;  
        
        SBP_SampleKitRelatedListController.getAllSampleKits(c2.id);
        SBP_SampleKitRelatedListController.getCaseDetails(c2.id);
        SBP_SampleKitRelatedListController.createNewSamples(sampleKit.id,barrel.Id);//Added by mahesh as part of createNewSamples enhancement
        SBP_SampleKitRelatedListController.getSampleDetails(c2.id);//Added by mahesh as part of createNewSamples enhancement
        SBP_SampleKitRelatedListController.DeleteSampleKitRecord(sample2.id);

    }

}